# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b25eb366bd263a09a24e6f94571a58fde7643b2babbcb445864b09e14f521a90cbd11744f3d8cbdab03c9721659b627ba84b984746e9bf1fda299d3ff095e2c9

test:
  secret_key_base: b6ada493a4fd65bdf49e2880e658c89f8436152f22053fc017f10ab9be9751eb40dade5791bca87075ee7e473c4a4a7b86c99e5e796ca19dcdb89db8a382bc6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
